[tox]
minversion = 3.20
envlist = py39
skipsdist = true

[testenv]
passenv =
    HOME
    USER
    PATH
    TERM
    container
deps =
    ansible-core==2.14.18
    ansible-compat==2.2.7
    molecule==4.0.4
    molecule-podman==2.0.3
    yamllint==1.37.1
commands =
    ansible-galaxy collection install containers.podman
    molecule test -s podman
