---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Include vector role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
