---
- name: Prepare Podman container
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Install Python and sudo on Ubuntu
      ansible.builtin.raw: >
        /bin/sh -c "apt-get update &&
        apt-get install -y python3 sudo"
      changed_when: false
